### ISSUE TITLE
[Discussion] : Approach to installation.

### ISSUE THREAD

**Issue by andrewtarzia** [EISy-as-Py/hardy#10]
Further to #9, I found that the installation instructions (README, and the two pages at https://hardy.readthedocs.io/en/latest/index.html) were not entirely consistent.

**Comment by amoeez** [comment]
@andrewtarzia thank you for pointing that out. I hope the installation instructions appear consistent now.

**Comment by andrewtarzia** [comment]
Thank you, sorted!
