### ISSUE TITLE
[Discussion] : Provide example trained models.

### ISSUE THREAD

**Issue by andrewtarzia** [EISy-as-Py/hardy#11]
Hello!

** Your Use-Case **
Reviewing this software is difficult for me because I do not currently have the infrastructure to complete the model training and I am struggling to get started with the software based on the available examples. #3 suggests there are some more tutorials/examples coming - will these include trained models to perform the data reporting?

**Comment by amoeez** [comment]
@andrewtarzia Yes, we plan to include trained models. For now, we've created a temporary Google Colab notebook (https://colab.research.google.com/drive/1XzlhTitEmeSmhieP1njmsHPk24weFGiL?usp=sharing) until we find an appropriate location to host this data. The notebook includes the performance comparison of trained models on both RGB and Cartesian Coordinate representation for Small Angle X-Ray Scattering (SAXS) simulated data. Please note that you'll be downloading these trained models into your own drive, so these should be accessible to you. I hope this helps. Please reach out if there are any other questions.

**Comment by andrewtarzia** [comment]
Thank you @amoeezuw, I will have a run through it soon to see if there are issues.

**Comment by andrewtarzia** [comment]
@amoeezuw are there examples for making predictions on a new piece of data?

**Comment by amoeez** [comment]
@andrewtarzia please find the example for a new data set using trained model on following google colab link (https://colab.research.google.com/drive/1zIIDerpRz28VOp5KQXyS6LkxbJZR5cqB?usp=sharing). The tutorial has also been added in the documentation. We found a bug while reviewing this which didn't allowed us to use the previously trained models. It has now been resolved and you may need to reinstall the HARDy if you intend to use it on the local machine. Please let me know if you've further questions. Thank you

**Comment by andrewtarzia** [comment]
That notebook works! Thank you. I think this tool is very useful but the usability really comes from good examples like this that guide a new user through the process for this test case.
