### ISSUE TITLE
[BUG] : Conda installation failed: problem with ResolvePackageNotFound: keras-tuner==1.0.1 

### ISSUE THREAD

**Issue by alberto-battistel** [EISy-as-Py/hardy#13]
**Describe the bug**
Fail to install via conda. 

**To Reproduce**
In terminal create a fresh environment:

`conda create --name joss_HARDy`

Activate the environment:

`conda activate joss_HARDy`

then run:

`conda install -c pozzorg hardy`

It gives:

> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: - 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed
> 
> ResolvePackageNotFound: 
>   - keras-tuner==1.0.1
> 

**System information**
> OS: Manjaro Linux x86_64 
> Host: 20AWS1J001 ThinkPad T440p 
> Kernel: 5.4.173-1-MANJARO 
> conda 4.11.0

**Comment by amoeez** [comment]
Hi @alberto-battistel,
When you create the environment, can you enforce python==3.7 into the conda argument, like the one below?

`conda create --name joss_HARDy python==3.7`

**Comment by alberto-battistel** [comment]
Hi @amoeezuw,
yes, 

`conda create --name joss_HARDy python==3.7`

works, but after
 
`conda activate joss_HARDy`

and
 
`conda install -c pozzorg hardy`

I get:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: \ 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                                       
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.33=0
>   - feature:|@/linux-64::__glibc==2.33=0
> 
> Your installed version is: 2.33

**Comment by amoeez** [comment]
Hi @alberto-battistel,

After you activate the environment, can you run either:

`pip install .` from the hardy directory or

`python3.7 setup.py install` instead of conda install.

**Comment by alberto-battistel** [comment]
Ok, both `pip install .` and `python3.7 setup.py install` worked.
running `python -c "import hardy"` gives:

> Using TensorFlow backend.

running from the hardy folder:

`jupyter notebook`

and selecting `How_to_make_predictions_using_trained_model.ipynb` works as expected in both cases.

Thank you very much!
