### ISSUE TITLE
[BUG] : GitHub repository installation failed: Permission denied

### ISSUE THREAD

**Issue by alberto-battistel** [EISy-as-Py/hardy#14]
**Describe the bug**
The installation via GitHub repository failed because of Permission denied.

**To Reproduce**
Following the installation instruction.
In the terminal:
`git clone https://github.com/EISy-as-Py/hardy.git`

`cd hardy`

`git checkout v1.0`

`python setup.py install`

This gives:

> /usr/lib/python3.10/distutils/dist.py:274: UserWarning: Unknown distribution option: 'description_content_type'
>   warnings.warn(msg)
> running install
> /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> /usr/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: '/usr/lib/python3.10/site-packages/test-easy-install-21091.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /usr/lib/python3.10/site-packages/
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html
> 
> Please make the appropriate changes for your system and try again.
> 

**Expected behavior**
The installation did not go through and one possible solution is to run the last step with administration rights or to change the installation directory.

**System info:**
OS: Manjaro Linux x86_64
Host: 20AWS1J001 ThinkPad T440p
Kernel: 5.4.173-1-MANJARO

**Comment by amoeez** [comment]
@alberto-battistel running the last command with administrative rights like `sudo python setup.py install` will resolve the issue.

However, through the information you provided above, I have noticed that your default python version is 3.10 which won't be compatible with HARDy

**Comment by alberto-battistel** [comment]
Yes, my default python version is 3.10.
I am going to flash a drive with an Ubuntu system and try one more time.

**Comment by amoeez** [comment]
@alberto-battistel
We've some binder ready notebooks for testing of less computationally intensive functionalities, if you would like to use. Binder uses Ubuntu18.04 so it will save some of your time. The binder link is as follow:
https://mybinder.org/v2/gh/EISy-as-Py/hardy/v1.0

Following two notebooks are binder ready in `hardy/doc/examples`
`How_to_make_predictions_using_trained_model.ipynb`
`using_data_reporting.ipynb`

The rendering of these notebooks are available in the documentations:
https://hardy.readthedocs.io/en/latest/examples/How_to_make_predictions_using_trained_model.html
https://hardy.readthedocs.io/en/latest/examples/using_data_reporting.html

Thank you.

**Comment by alberto-battistel** [comment]
I failed with the flashing of a drive with an Ubuntu system. It requires persistent storage on the drive and apparently I cannot get it to work.
However, I tried out the Binder and everything works as expected.

Thank you,
Alberto
