### ISSUE TITLE
[Discussion] : Does your `setup.py` need to mention dependencies?

### ISSUE THREAD

**Issue by dacb** [EISy-as-Py/hardy#5]
All in the tin.

I wonder if you should include some dependencies in the `setup.py` so pip can automatically install them?

**Comment by amoeez** [comment]
Hi @dacb,

I can imagine the use of it, though wouldn't it slow down new modules integration? Moreover, we provide conda install feature to cater the complex dependencies we have, do you still think it would be good idea to include some of those in setup.py?

**Comment by dacb** [comment]
Wow, I forgot about this comment.  I think it is good form to include them if someone wants to pip install vs conda.

**Comment by amoeez** [comment]
@dacb

The dependencies have been added to the setup.py file.
